TMS/TMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('supervisor/', include('supervisor.urls')),
]

TMS/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('project/', views.project_view, name='project'),
    path('timesheet/', views.timesheet_view, name='timesheet_view'),
    path('profile/', views.profile_view, name='profile'),
    path('addtimesheet/', views.add_timesheet, name='addtimesheet'),
    path('edittimesheet/',views.edit_timesheet, name='edittimesheet'),
    path('logout/', views.logout_view, name='logout'),
]

TMS/supervisor/urls.py
from django.urls import path
from . import views


app_name = 'supervisor'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('project/', views.project_view, name='project'),
    path('timesheet/', views.get_timesheets_view, name='get_timesheets'),
    # path('profile/', views.profile_view, name='profile'),
    path('manageproject/', views.manageproject_view, name='manageproject'),
    path('edittimesheet/',views.get_emp_summaries_view, name='get_emp_summaries'),
    path('logout/', views.logout_view, name='logout'),
]

TMS/supervisor/models.py
from django.db import models
from accounts.models import Profile, Project
# Create your models here.
class Supervisor(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    sup_name = models.CharField(max_length=200, default='sup_name')
    projects = models.ManyToManyField(Project)
    def __str__(self):
        return self.sup_name

TMS/supervisor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Supervisor
from accounts.models import Profile, Project, TimeSheet
from django.contrib.auth.models import User
from datetime import datetime, date
# Create your views here.

# This login_view gets the request and checks if the requested method is an get or postself.
# If the method is get return the login pageself.
# Else if post then check the credentials, if error then return to login page with message
#                                          else send the view page.
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        # Retrieve the profile object by using user and
        # use the profile object returned to check if the profile objects
        # is in the supervisor object. If the user is not None and returned
        # user_supervisor query set length is 1 then we login the user
        profile = Profile.objects.filter(user=user)
        if len(profile) == 0: return render(request, 'supervisor/login.html', {'error': 'Username or Password is incorrect'})
        profile = profile[0]
        user_supervisor = Supervisor.objects.filter(user=profile)
        if user is not None and (len(user_supervisor) == 1):
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return render(request, 'supervisor/view.html')
        else:
            return render(request, 'supervisor/login.html', {'error': 'Username or Password is incorrect'})
    else:
        return render(request, 'supervisor/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'supervisor/login.html', {'error':'logged out succesfully'})

def project_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pass
        else:
            user = User.objects.get(username=request.user.username)
            profile = Profile.objects.filter(user=user)
            supervisor = Supervisor.objects.filter(user=profile[0])[0]
            projects = supervisor.projects.all()
            return render(request, 'supervisor/project.html', {'projects':projects})
    else:
        return render(request, 'supervisor/login.html', {'error': 'Login to access the page'})

# check if the user is logged in else return him login page
# else return the all the timesheets the user requested for a project
def get_timesheets_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
             pass
        else:
            project_id = request.GET['project_id']
            project = Project.objects.filter(id=project_id)[0]
            timesheets = TimeSheet.objects.filter(project=project)
            return render(request, 'supervisor/timesheet.html', {'timesheets':timesheets})
    else:
        return render(request, 'supervisor/login.html', {'error': 'Login to access the page'})


def get_emp_summaries_view(request):
    if request.method == 'POST':
        pass
    else:
        project_id = request.GET['project_id']
        project = Project.objects.filter(id=project_id)[0]
        timesheets = TimeSheet.objects.filter(project=project)
        emp_summaries = {}
        for timesheet in timesheets:
            if timesheet.emp_name in emp_summaries:
                emp_summaries[timesheet.emp_name] += datetime.combine(date.today(),timesheet.end_time) - datetime.combine(date.today(),timesheet.start_time)
                print(timesheet.emp_name,emp_summaries[timesheet.emp_name])
            else:
                emp_summaries[timesheet.emp_name] = datetime.combine(date.today(),timesheet.end_time) - datetime.combine(date.today(),timesheet.start_time)
                print(timesheet.emp_name,emp_summaries[timesheet.emp_name])
        return render(request, 'supervisor/Summaries.html',{'emp_summaries':emp_summaries,'project_name':project.project_name})

#check the user is logged in else return him to login page
# check if the request is POST else return the project requested
# if POST then remove/add the Selected employees from project
def manageproject_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            # if the button clicked is delete_emp then delete the employees from
            # project else if add_emp then add employees to project
            if 'delete_emp' in request.POST:
                employee_ids = request.POST.getlist('employees')
                project_id = request.POST['project_id']
                project = Project.objects.filter(id=project_id)[0]
                for e_id in employee_ids:
                    project.employees.remove(e_id)
                employees = Profile.objects.all()
                employees_inproject =  project.employees.all()
                employees_could_add =  employees.difference(employees_inproject)
                return render(request, 'supervisor/manageproject.html',{'project':project, 'employees_could_add':employees_could_add,'error':'Selected users are removed'})
            elif 'add_emp' in request.POST:
                employee_ids = request.POST.getlist('employees')
                project_id = request.POST['project_id']
                project = Project.objects.filter(id=project_id)[0]
                for e_id in employee_ids:
                    project.employees.add(e_id)
                employees = Profile.objects.all()
                employees_inproject =  project.employees.all()
                employees_could_add =  employees.difference(employees_inproject)
                return render(request, 'supervisor/manageproject.html',{'project':project,'employees_could_add':employees_could_add, 'error':'Selected users are removed'})
        else:
            if 'manage_project' in request.GET:
                employees = Profile.objects.all()
                project_id = request.GET.get('project_id')
                project = Project.objects.filter(id=project_id)[0]
                employees_inproject =  project.employees.all()
                employees_could_add =  employees.difference(employees_inproject)
                return render(request, 'supervisor/manageproject.html', {'project':project, 'employees_could_add':employees_could_add})

    else:
        return render(request, 'supervisor/login.html', {'error': 'Login to access the page'})

TMS/supervisor/templates/supervisor/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
  </head>

  <body class="text-center">
    <form action="{% url 'supervisor:login' %}" method="post">
        {% csrf_token %}
        <h1>Login as a supervisor</h1>
        {% if request.GET.next %}
            <input type="hidden" name="next", value={{request.GET.next}}>
        {% endif %}
        {% if error %}
          <h1 class="h3 mb-3 font-weight-normal">{{error}}</h1>
        {% endif %}
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
    </form>
  </body>
</html>

TMS/supervisor/templates/supervisor/manageproject.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <h1>Manage Project</h1>
    <h1>Editing Project {{project.project_name}}</h1>
    <form action="{% url 'supervisor:manageproject' %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next", value={{request.GET.next}}>
        {% endif %}
        <input type="hidden" name="project_id", value={{project.id}}>
        <div class="form-group row">
          <label for="projectName" class="col-sm-2 col-form-label">Project Name</label>
          <div class="col-sm-10">
            <input type="text" name="project" class="form-control-plaintext" id="projectName" value="{{project.project_name}}">
          </div>
        </div>
        <h6>Manage the employees list:</h6>
        <p>Check the boxes to remove employees:</p>
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              {% for employee in employees_could_add.all %}
                <input type="checkbox" name="employees" value="{{employee.id}}"> {{employee}}<br>
              {% endfor%}
              <button class="btn btn-primary" name="add_emp" type="submit">Add Employees</button>
            </div>
            <div class="col-xs-6">
              {% for employee in project.employees.all %}
                <input type="checkbox" name="employees" value="{{employee.id}}"> {{employee}}<br>
              {% endfor%}
              <button class="btn btn-danger" name="delete_emp" type="submit">Delete</button>
            </div>
          </div>
        </div>
    </form>
    <a href="{% url 'accounts:logout' %}">Logout</a>
 </body>
</html>

TMS/supervisor/templates/supervisor/project.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body class="text-center">
      {% if projects %}
      {% for project in projects %}
        <div class="row">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras accumsan ex quis enim luctus sodales.
                  Interdum et malesuada fames ac ante ipsum primis in faucibus. </p>
                  <div class="row">
                    <div class="col-sm-4">
                      <form action="{% url 'supervisor:manageproject' %}" method="get">
                         <input type="hidden" name="project_id" value="{{ project.id }}">
                         <input type="submit" class="btn btn-primary" name = "manage_project" value="Manage Project">
                      </form>
                    </div>
                    <div class="col-sm-4">
                      <form action="{% url 'supervisor:get_emp_summaries' %}" method="get">
                         <input type="hidden" name="project_id" value="{{ project.id }}">
                         <input type="submit" class="btn btn-primary" name="get_emp_summaries" value="Generate Summaries">
                      </form>
                    </div>
                    <div class="col-sm-4">
                      <form action="{% url 'supervisor:get_timesheets' %}" method="get">
                         <input type="hidden" name="project_id" value="{{ project.id }}">
                         <input type="submit" class="btn btn-primary" name="get_timesheets" value="Get Timesheets">
                      </form>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      {%endfor%}

      {%else%}
        <h2>You are not in any project currently</h2>
      {%endif%}
      <br>
      <a href="{% url 'supervisor:logout' %}">Logout</a>
    </body>
</html>

TMS/supervisor/templates/supervisor/summaries.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body class="text-center">
      <h1>TimeSheet for Employees working on {{project_name}}</h1>
      {% if emp_summaries %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Employee Name</th>
            <th scope="col">Hours Worked</th>
          </tr>
        </thead>
        {% for key,value in emp_summaries.items %}
        <tr>
          <td>{{key}}</td>
          <td>{{value}}</td>
        </tr>
        {%endfor%}
        </thead>
      </table>
      {%else%}
       <h1>There are not Timesheets available</h1>
      {%endif%}
      <a href="{% url 'supervisor:logout' %}">Logout</a>
  </body>
</html>

TMS/supervisor/templates/supervisor/timesheet.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body class="text-center">
      <h2>Your time sheets</h2>
        {%if error%}
          <h2>{{error}}</h2>
        {%endif%}

        {% if timesheets %}
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Timesheet #</th>
                <th scope="col">Employee Name</th>
                <th scope="col">Project</th>
                <th scope="col">Date</th>
                <th scope="col">From</th>
                <th scope="col">To</th>
              </tr>
              {% for timesheet in timesheets %}
              <form action="" method="get">
                <tr>
                  <td name="timesheet_id">{{timesheet.id}}</td>
                  <td name="emp_name">{{timesheet.emp_name}}</td>
                  <td name="project_name">{{ timesheet.project }}</td>
                  <td name="date"> {{ timesheet.date|date:"Y-m-d" }}</td>
                  <td name="from">{{timesheet.start_time|time:"h:i"}}</td>
                  <td name="to">{{ timesheet.end_time|time:"h:i" }}</td>
                  <input type="hidden" name="timesheet_id" value="{{timesheet.id}}">
                </tr>
              </form>
              {%endfor%}
            </thead>
          </table>
        {% else %}
          <h2>You donot have any time sheets available to view</h2>
        {% endif %}
        <br>
        <a href="{% url 'accounts:logout' %}">Logout</a>
    </body>
  </html>

TMS/supervisor/templates/supervisor/view.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <a href="{% url 'supervisor:project' %}">View Projects you are supervising</a>
    <br>
    <a href="{% url 'accounts:timesheet_view' %}">View Timesheets</a>
    <br>
    <a href="{% url 'accounts:profile' %}">Profile</a>
    <br>
    <a href="{% url 'supervisor:logout' %}">Logout</a>
 </body>
</html