TMS/TMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('supervisor/', include('supervisor.urls')),
]

TMS/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('project/', views.project_view, name='project'),
    path('timesheet/', views.timesheet_view, name='timesheet_view'),
    path('profile/', views.profile_view, name='profile'),
    path('addtimesheet/', views.add_timesheet, name='addtimesheet'),
    path('edittimesheet/',views.edit_timesheet, name='edittimesheet'),
    path('logout/', views.logout_view, name='logout'),
]

TMS/accounts/models.py
from django.db import models
from django.db.models.signals import post_save # we will now define signals so our Profile model will be
from django.dispatch import receiver           #automatically created/updated when we create/update User instances.
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_name = models.CharField(max_length=500)
    gender = models.CharField(max_length=10)
    job_position = models.CharField(max_length=20)
    salary = models.IntegerField()

    def __str__(self):
        return self.emp_name

class Project(models.Model):
    project_name = models.CharField(max_length=200)
    employees = models.ManyToManyField(Profile)

    def __str__(self):
        return self.project_name

class TimeSheet(models.Model):
    profile = models.ManyToManyField(Profile)
    emp_name = models.CharField(max_length=100, default='emp_name')
    date  = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    #project_name = models.CharField(max_length=100, default='project_name')
    def __str__(self):
        return self.emp_name + ' ' + self.project.project_name +' '+ str(self.date)

TMS/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Profile, Project, TimeSheet
from django.contrib.auth.models import User
import datetime
# Create your views here.
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return render(request, 'accounts/view.html')
        else:
            return render(request, 'accounts/login.html', {'error': 'Username or Password is incorrect'})
    else:
        return render(request, 'accounts/login.html')

# check if the user is is_authenticated
# else render the login page
# if logged in send him the projects he is involved in.
def project_view(request):
    if request.user.is_authenticated:
        id = request.user.id
        emp_profile = Profile.objects.filter(user=id)[0] # get the profile object of the logged in user
        projects = emp_profile.project_set.all()         # use the profile object to get his projects
        return render(request, 'accounts/project.html', {'projects':projects})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

# Checks if the user is logged in, else return him/her to login page
def timesheet_view(request):
    if request.user.is_authenticated:
        profile = Profile.objects.filter(user=request.user)[0]
        print(profile)
        timesheets = TimeSheet.objects.filter(profile=profile)
        print(timesheets)
        return render(request, 'accounts/timesheet.html', {'timesheets':timesheets})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

# check if the user is logged in else return him to the login page
# if request.method is GET send him the accounts/add_timesheet.html which has the form
# to submit new TimeSheet
# if request.method is POST write the timesheet object received to the database
def add_timesheet(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            if request.POST['from'] >= request.POST['to']:
                project_id = request.POST.get('project_id')
                project = Project.objects.filter(id=project_id)[0]
                return render(request, 'accounts/add_timesheet.html', {'project':project,'error':'start time should be less than end time'})
            timesheet = TimeSheet()
            timesheet.date = request.POST['date']
            timesheet.start_time = request.POST['from']
            timesheet.end_time = request.POST['to']
            timesheet.project = Project.objects.filter(id=request.POST.get('project_id'))[0]
            timesheet.emp_name = request.user.username
            timesheet.save()
            profile = Profile.objects.filter(user=request.user)[0]
            timesheet.profile.add(profile)
            timesheet.save()
            id = request.user.id
            print(timesheet.profile, request.user)
            emp_profile = Profile.objects.filter(user=id)[0] # get the profile object of the logged in user
            projects = emp_profile.project_set.all()         # use the profile object to get his projects
            return render(request, 'accounts/project.html', {'projects':projects})
        else:
            project_id = request.GET.get('project_id')
            project = Project.objects.filter(id=project_id)[0]
            return render(request, 'accounts/add_timesheet.html', {'project':project})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

# check if the user is logged in else return him to the login page
# if the request.method is GET, get the timesheet the user requested from database
# check if the grace days are no more than 14 days. if more than 14 days send him/her to previous page
# with an error messaage
# if not then send him the requested timesheet to be edited.
def edit_timesheet(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            timesheet_id = request.POST.get('timesheet_id')
            timesheet = TimeSheet.objects.filter(id=timesheet_id)[0]
            timesheet.user = request.user.username
            timesheet.date = request.POST['date']
            timesheet.start_time = request.POST['from']
            timesheet.end_time = request.POST['to']
            project = Project.objects.filter(project_name = request.POST.get('project_name'))[0]
            timesheet.project = project
            timesheet.save()
            profile = Profile.objects.filter(user=request.user)[0]
            timesheets = TimeSheet.objects.filter(profile=profile)
            return render(request, 'accounts/timesheet.html', {'timesheets':timesheets})
        else:
            timesheet_id = request.GET.get('timesheet_id')
            print(1, timesheet_id)
            timesheet = TimeSheet.objects.filter(id=timesheet_id)[0]
            grace_days = datetime.datetime.now().date()-timesheet.date
            # if the requested timesheet's date to be edited is more than 13 days or 2 weeks
            # then return the timesheets apge to user saying that, he canot edit that timesheet.
            if grace_days.days > 13:
                profile = Profile.objects.filter(user=request.user)[0]
                timesheets = TimeSheet.objects.filter(profile=profile)
                return render(request, 'accounts/timesheet.html', {'error':'You can\'t edit your two weeks past timesheet', 'timesheets':timesheets})
            return render(request, 'accounts/edittimesheet.html', {'timesheet':timesheet})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

# check if the user is logged in else return him to the login page
# get the profile object of the user and send it to him/her.
def profile_view(request):
    if request.user.is_authenticated:
        username = User.objects.get(username=request.user.username)
        profile = Profile.objects.filter(user=username)
        return render(request, 'accounts/profile.html', {'profile':profile[0]})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})



def logout_view(request):
    logout(request)
    return render(request, 'accounts/login.html', {'error':'logged out succesfully'})

TMS/accounts/templates/accounts/add_timesheet.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <h1>Add new timesheet</h1>

    {% if error %}
        {{error}}
    {% endif %}
    <h1>Adding timesheet for {{project}}</h1>
    <form action="{% url 'accounts:addtimesheet' %}" method="post"  >
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next", value={{request.GET.next}}>
        {% endif %}
        <input type="hidden" name="project_id" value='{{project.id}}'>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">Date</label>
          <div class="col-md-3">
            <input type="date" class="form-control" name="date" id="inputEmail3" placeholder="Date">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">From</label>
          <div class="col-md-3">
            <input type="time" class="form-control" name="from" id="inputEmail3" placeholder="From">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">To</label>
          <div class="col-md-3">
            <input type="time" class="form-control" name="to" id="inputEmail3" placeholder="To">
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-8">
            <button type="submit" class="btn btn-primary">Add Timesheet</button>
          </div>
        </div>
        <!-- Date : <input type="date" name="date">
        From : <input name="from" type="time">
        To   : <input name="to" type="time">
        <input type="submit" name="Add Timesheet"> -->
    </form>
    <br>
    <a href="{% url 'accounts:logout' %}">Logout</a>
  </body>
</html>

TMS/accounts/templates/accounts/edittimesheet.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <h1>Edit timesheet</h1>
    {% if error %}
        <h1>{{error}}</h1>
    {% endif %}

    <h1>Ediiting timesheet for {{timesheet.project}}</h1>
    <form action="{% url 'accounts:edittimesheet' %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next", value={{request.GET.next}}>
        {% endif %}
        <input type="hidden" name="timesheet_id", value={{timesheet.id}}>
        <input type="hidden" name="project_name" value='{{timesheet.project}}'>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">Date</label>
          <div class="col-md-3">
            <input type="date" class="form-control" name="date" id="inputEmail3" value="{{timesheet.date|date:"Y-m-d"}}" placeholder="Date">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">From</label>
          <div class="col-md-3">
            <input type="time" class="form-control" name="from" id="inputEmail3" value="{{timesheet.start_time|time:"h:i"}}" placeholder="From">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">To</label>
          <div class="col-md-3">
            <input type="time" class="form-control" name="to" id="inputEmail3" value="{{timesheet.end_time|time:"h:i"}}" placeholder="To">
          </div>
        </div>
        <!-- Date : <input type="date" name="date" value="{{timesheet.date|date:"Y-m-d"}}">
        From : <input name="from" type="time" value="{{timesheet.start_time|time:"h:i"}}">
        To   : <input name="to" type="time" value="{{timesheet.end_time|time:"h:i"}}"> -->
        <div class="form-group row">
          <div class="col-md-8">
            <button type="submit" class="btn btn-primary">Add Timesheet</button>
          </div>
        </div>
        <!-- <input type="submit" name="Add Timesheet"> -->
    </form>
    <br>
    <a href="{% url 'accounts:logout' %}">Logout</a>
  </body>
</html>

TMS/accounts/templates/accounts/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
  </head>

  <body class="text-center">
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden"   name="next", value={{request.GET.next}}>
        {% endif %}
        {% if error %}
          <h1 class="h3 mb-3 font-weight-normal">{{error}}</h1>
        {% endif %}
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
    </form>
  </body>
</html>

TMS/accounts/templates/accounts/profile.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

  </head>

  <body class="text-center">
    <h1>Profile page</h1>
    <form class="" action="" method="post">
      <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticEmail" value={{ profile.user }}>
        </div>
      </div>
      <div class="form-group row">
        <label for="" class="col-sm-2 col-form-label">Employee Name</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="" value={{ profile.emp_name }}>
        </div>
      </div>
      <div class="form-group row">
        <label for="" class="col-sm-2 col-form-label">Employee Name</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="" value={{ profile.emp_name }}>
        </div>
      </div>
      <div class="form-group row">
        <label for="" class="col-sm-2 col-form-label">Gender</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="" value={{ profile.gender }}>
        </div>
      </div>
      <div class="form-group row">
        <label for="" class="col-sm-2 col-form-label">Salry</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="" value={{ profile.salary }}>
        </div>
      </div>
    </form>
    <a href="{% url 'accounts:logout' %}">Logout</a>
  </body>
</html>

TMS/accounts/templates/accounts/project.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body class="text-center">
      {% if projects %}
          {% for project in projects %}
             <form action="{% url 'accounts:addtimesheet' %}" method="get">
                <div class="row">
                  <div class="col-sm-6">
                    <div class="card">
                      <div class="card-body">
                        <input type="hidden" name="project_id" value="{{ project.id }}">
                        <h5 class="card-title">{{ project.project_name }}</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras accumsan ex quis enim luctus sodales.
                          Interdum et malesuada fames ac ante ipsum primis in faucibus. </p>
                        <input type="submit" class="btn btn-primary" value="Add Timesheet">
                      </div>
                    </div>
                  </div>
              </div>
              </form>
              <!-- <input type="radio" name = "project_id" value="{{ project.id }}">{{ project.project_name }}<br> -->
          {%endfor%}
              <!-- <input type="submit" value="Add Timesheet"> -->
      {%else%}
          <h2>You are not in any project currently</h2>
      {%endif%}
      <br>
      <a href="{% url 'accounts:logout' %}">Logout</a>
    </body>
</html>

TMS/accounts/templates/accounts/timesheet.html
<h2>Your time sheets</h2>

{%if error%}
  <h2>{{error}}</h2>
{%endif%}

<form action="{% url 'accounts:edittimesheet' %}" method="get">
{% if timesheets %}
  {% for timesheet in timesheets %}
      <input type="radio" name = "timesheet_id" value="{{ timesheet.id }}">{{ timesheet.emp_name }} - {{ timesheet.date|date:"Y-m-d" }} - {{ timesheet.start_time|time:"h:i" }} - {{ timesheet.end_time|time:"h:i" }} - {{ timesheet.project }}<br>
  {%endfor%}
      <input type="submit" value="Edit Timesheet">
  </form>
{% else %}
  <h2>You donot have any time sheets available to view</h2>
{% endif %}
<br>
<a href="{% url 'accounts:logout' %}">Logout</a>

TMS/accounts/templates/accounts/view.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>

    <body class="text-center">
      <div class="container">
        <div class="row">
          <div class="col">
            <a href="{% url 'accounts:project' %}">View Projects</a>
          </div>
          <div class="col">
            <a href="{% url 'accounts:timesheet_view' %}">View Timesheets</a>
          </div>
          <div class="col">
            <a href="{% url 'accounts:profile' %}">Profile</a>
          </div>
        </div>
      </div>
      <a href="{% url 'accounts:logout' %}">Logout</a>
    </body>
</html>